"""
Subtitle and closed-caption parser for the ytdownloader package.

Handles parsing of YouTube caption tracks from player responses, downloading
subtitle files in YouTube's native XML or json3 formats, and converting them
to the widely-supported SubRip (SRT) format.

Typical usage::

    from ytdownloader.subtitle_parser import (
        SubtitleTrack,
        get_caption_tracks,
        download_subtitle,
    )

    tracks = get_caption_tracks(player_response)
    for track in tracks:
        path = download_subtitle(track, "subtitles/", format="srt")
        print(f"Saved: {path}")
"""

from __future__ import annotations

import logging
import os
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Any, Optional
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

import requests

from .exceptions import SubtitleError
from .logger import get_logger

__all__ = [
    "SubtitleTrack",
    "SubtitleCue",
    "parse_caption_tracks",
    "get_caption_tracks",
    "download_subtitle",
    "convert_to_srt",
    "list_available_tracks",
]

_logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_DEFAULT_TIMEOUT: int = 30
_DEFAULT_CHUNK_SIZE: int = 4096

_CAPTION_TRACKS_KEY: str = "captions"
_CAPTION_PLAYER_KEY: str = "playerCaptionsTracklistRenderer"
_CAPTION_TRACKS_LIST_KEY: str = "captionTracks"
_AUDIO_TRACK_KEY: str = "audioTracks"

_TRANSCRIPT_XML_NS: dict[str, str] = {
    "tt": "http://www.w3.org/ns/ttml",
    "default": "http://www.w3.org/ns/ttml#default",
}

_XML_CUE_TAG: str = "p"
_XML_TEXT_TAG: str = "s"

_JSON3_EVENTS_KEY: str = "events"
_JSON3_TEXT_KEY: str = "segs"
_JSON3_UTF8_KEY: str = "utf8"

_SRT_TIME_PATTERN: str = re.compile(
    r"^(?P<h>\d+):(?P<m>\d+):(?P<s>\d+),(?P<ms>\d+)$"
)

_NON_SPEECH_FILLERS: frozenset[str] = frozenset(
    {"[music]", "[applause]", "[laughing]", "[silence]", "[noise]", "[signal]"}
)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class SubtitleTrack:
    """Represents a single YouTube caption or subtitle track.

    Attributes:
        url: Direct URL to the subtitle file (XML or json3 format).
        lang: Human-readable language name (e.g. ``"English"``).
        lang_code: BCP-47 language code (e.g. ``"en"``, ``"es-419"``).
        is_auto: ``True`` when the track was auto-generated by YouTube's ASR.
        is_translated: ``True`` when the track is a machine translation.
        kind: ``"asr"`` for auto-generated, ``"forced"`` for forced, or
            ``None``/empty for manually uploaded captions.
    """

    url: str
    lang: str
    lang_code: str
    is_auto: bool = False
    is_translated: bool = False
    kind: str = ""

    def __post_init__(self) -> None:
        if not self.url:
            raise ValueError("SubtitleTrack.url must be a non-empty string.")
        if not self.lang_code:
            raise ValueError("SubtitleTrack.lang_code must be a non-empty string.")

    def __repr__(self) -> str:
        flags = []
        if self.is_auto:
            flags.append("auto")
        if self.is_translated:
            flags.append("translated")
        if self.kind:
            flags.append(f"kind={self.kind!r}")
        flag_str = f" [{', '.join(flags)}]" if flags else ""
        return (
            f"SubtitleTrack(lang={self.lang_code!r}, "
            f"name={self.lang!r}{flag_str}, url={self.url[:60]!r}...)"
        )


@dataclass
class SubtitleCue:
    """A single timed subtitle cue extracted from a caption file.

    Attributes:
        index: Zero-based index of this cue within the subtitle file.
        start_ms: Start time in milliseconds.
        end_ms: End time in milliseconds.
        text: The subtitle text.  Newlines within a cue are represented as
            ``\\n`` and will be rendered as separate SRT lines.
    """

    index: int
    start_ms: int
    end_ms: int
    text: str = ""

    def __post_init__(self) -> None:
        if self.end_ms <= self.start_ms:
            self.end_ms = self.start_ms + 1000

    @property
    def start_seconds(self) -> float:
        """Start time as floating-point seconds."""
        return self.start_ms / 1000.0

    @property
    def end_seconds(self) -> float:
        """End time as floating-point seconds."""
        return self.end_ms / 1000.0

    def __repr__(self) -> str:
        return (
            f"SubtitleCue(index={self.index}, "
            f"start={self.start_seconds:.3f}s, end={self.end_seconds:.3f}s, "
            f"text={self.text[:30]!r})"
        )


# ---------------------------------------------------------------------------
# Public API – track discovery
# ---------------------------------------------------------------------------


def parse_caption_tracks(captions_data: dict) -> list[SubtitleTrack]:
    """Parse the ``captions`` block of a YouTube player response.

    The *captions_data* argument should be the value of
    ``player_response["captions"]``.  Returns an empty list when the block
    is absent or contains no tracks.

    Args:
        captions_data: The ``"captions"`` dict from a YouTube player response.

    Returns:
        A (possibly empty) list of :class:`SubtitleTrack` objects.

    Raises:
        SubtitleError: If *captions_data* is not a mapping.
    """
    if not isinstance(captions_data, dict):
        _logger.warning(
            "Expected captions_data to be a dict; got %s. Returning empty list.",
            type(captions_data).__name__,
        )
        return []

    renderer: dict = captions_data.get(_CAPTION_PLAYER_KEY, {})
    tracks_raw: list[dict] = renderer.get(_CAPTION_TRACKS_LIST_KEY, [])

    if not tracks_raw:
        _logger.debug("No caption tracks found in captions_data.")
        return []

    tracks: list[SubtitleTrack] = []
    for entry in tracks_raw:
        track = _parse_single_caption_entry(entry)
        if track is not None:
            tracks.append(track)

    _logger.info("Found %d caption track(s).", len(tracks))
    return tracks


def get_caption_tracks(player_response: dict) -> list[SubtitleTrack]:
    """Extract caption tracks directly from a YouTube player response dict.

    This is the preferred entry point for callers who already have the full
    ``ytInitialPlayerResponse`` object.  Handles missing or malformed data
    gracefully by returning an empty list.

    Args:
        player_response: The full YouTube player response dictionary
            (typically the ``ytInitialPlayerResponse`` JavaScript object).

    Returns:
        A (possibly empty) list of :class:`SubtitleTrack` objects.
    """
    if not isinstance(player_response, dict):
        _logger.warning(
            "Expected player_response to be a dict; got %s. Returning empty list.",
            type(player_response).__name__,
        )
        return []

    captions_data: dict = player_response.get(_CAPTION_TRACKS_KEY, {})
    return parse_caption_tracks(captions_data)


def list_available_tracks(
    tracks: list[SubtitleTrack],
) -> list[dict[str, Any]]:
    """Return a human-readable summary of available caption tracks.

    Args:
        tracks: A list of :class:`SubtitleTrack` objects.

    Returns:
        A list of dicts with keys ``index``, ``lang_code``, ``lang``,
        ``is_auto``, ``is_translated``, and ``kind``.
    """
    result: list[dict[str, Any]] = []
    for idx, track in enumerate(tracks):
        result.append(
            {
                "index": idx,
                "lang_code": track.lang_code,
                "lang": track.lang,
                "is_auto": track.is_auto,
                "is_translated": track.is_translated,
                "kind": track.kind or "(manual)",
            }
        )
    return result


# ---------------------------------------------------------------------------
# Public API – download and convert
# ---------------------------------------------------------------------------


def download_subtitle(
    track: SubtitleTrack,
    output_path: str,
    format: str = "srt",
    http_client: Any = None,
) -> str:
    """Download a subtitle track and convert it to the requested format.

    The file is fetched from ``track.url``, automatically detected as XML or
    json3, converted to the requested *format*, and written to *output_path*.

    Args:
        track: The :class:`SubtitleTrack` to download.
        output_path: Destination file path.  Parent directories are created
            automatically.  The extension may be omitted; the function appends
            ``.srt`` when *format* is ``"srt"``.
        format: Output format.  Currently only ``"srt"`` is supported.
        http_client: Optional pre-configured HTTP client with a ``get`` method
            compatible with :class:`requests.Session.get`.  When ``None`` a
            plain :class:`requests.Session` is used.

    Returns:
        The absolute path of the written file.

    Raises:
        SubtitleError: If the download fails, the format is unrecognised, or
            conversion to the requested format is not possible.
        ValueError: If *format* is not supported.
    """
    _logger.info(
        "Downloading subtitle track: lang=%s, is_auto=%s, format=%s",
        track.lang_code,
        track.is_auto,
        format,
    )

    format = format.lower().strip()
    if format not in ("srt",):
        raise ValueError(
            f"Unsupported subtitle format: {format!r}. " "Only 'srt' is currently supported."
        )

    output_abs = os.path.abspath(output_path)
    output_dir = os.path.dirname(output_abs)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    base, ext = os.path.splitext(output_abs)
    if format == "srt" and not ext:
        output_abs = f"{base}.srt"

    session = http_client if http_client is not None else requests.Session()

    try:
        response = session.get(
            track.url,
            timeout=_DEFAULT_TIMEOUT,
            headers={
                "User-Agent": (
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                "Referer": "https://www.youtube.com/",
                "Accept": "*/*",
            },
        )
        response.raise_for_status()
        raw_content: str = response.text
    except requests.exceptions.RequestException as exc:
        raise SubtitleError(
            f"Failed to download subtitle from {track.url!r}.",
            cause=exc,
        ) from exc

    detected_format = _detect_format(raw_content, track.url)
    _logger.debug("Detected subtitle format: %s", detected_format)

    try:
        if detected_format == "xml":
            cues = _parse_xml_caption(raw_content)
        elif detected_format == "json3":
            cues = _parse_json3_caption(raw_content)
        else:
            raise SubtitleError(
                f"Cannot parse subtitle format {detected_format!r} from {track.url!r}."
            )
    except SubtitleError:
        raise
    except Exception as exc:
        raise SubtitleError(
            f"Failed to parse subtitle content from {track.url!r}.",
            cause=exc,
        ) from exc

    if not cues:
        _logger.warning("Subtitle file contained no cues: %s", track.url)

    srt_content = convert_to_srt(cues)

    try:
        with open(output_abs, "w", encoding="utf-8") as fh:
            fh.write(srt_content)
    except OSError as exc:
        raise SubtitleError(
            f"Cannot write subtitle to {output_abs!r}: {exc}"
        ) from exc

    file_size = os.path.getsize(output_abs)
    _logger.info(
        "Subtitle saved: %s (%d bytes, %d cue(s)).",
        output_abs,
        file_size,
        len(cues),
    )
    return output_abs


def convert_to_srt(cues: list[SubtitleCue]) -> str:
    """Convert a list of :class:`SubtitleCue` objects to an SRT string.

    Args:
        cues: Ordered list of subtitle cues.

    Returns:
        A complete SRT file content as a string.
    """
    parts: list[str] = []
    for cue in cues:
        parts.append(_cue_to_srt_entry(cue))
    return "\n".join(parts) + "\n" if parts else ""


# ---------------------------------------------------------------------------
# Internal helpers – caption track parsing
# ---------------------------------------------------------------------------


def _parse_single_caption_entry(entry: dict) -> Optional[SubtitleTrack]:
    """Parse one element of the ``captionTracks`` list.

    Each entry has the form::

        {
            "baseUrl": "https://...",
            "name": {"simpleText": "English", "runs": [...]},
            "vssId": ".en",
            "languageCode": "en",
            "kind": "asr",          # optional
            "isTranslatable": true  # optional
        }

    Args:
        entry: Raw dict from ``captionTracks``.

    Returns:
        A :class:`SubtitleTrack`, or ``None`` if the entry is malformed.
    """
    if not isinstance(entry, dict):
        _logger.warning("Skipping malformed caption entry (not a dict): %r", entry)
        return None

    url: str = entry.get("baseUrl", "")
    if not url:
        _logger.warning("Skipping caption entry with empty baseUrl: %r", entry)
        return None

    name_obj: dict = entry.get("name", {})
    if isinstance(name_obj, dict):
        lang: str = name_obj.get("simpleText", name_obj.get("runs", [{}])[0].get("text", ""))
    elif isinstance(name_obj, str):
        lang = name_obj
    else:
        lang = ""

    vss_id: str = entry.get("vssId", "")
    lang_code = _extract_lang_code(vss_id, entry.get("languageCode", ""))

    kind: str = entry.get("kind", "") or ""
    is_translatable: bool = bool(entry.get("isTranslatable", False))

    is_auto: bool = kind == "asr" or (not kind and not lang)
    is_translated: bool = is_translatable and bool(lang_code) and bool(lang)

    return SubtitleTrack(
        url=url,
        lang=lang or lang_code,
        lang_code=lang_code,
        is_auto=is_auto,
        is_translated=is_translated,
        kind=kind,
    )


def _extract_lang_code(vss_id: str, fallback: str) -> str:
    """Extract the BCP-47 language code from a ``vssId`` field.

    YouTube ``vssId`` values look like ``".en"``, ``".es-419"``, or
    ``".a.id"`` (for Indonesian auto-generated).  The leading dot is
    stripped.

    Args:
        vss_id: The raw ``vssId`` string from the caption entry.
        fallback: Value to return when *vss_id* does not contain a code.

    Returns:
        A clean language code string.
    """
    if not vss_id:
        return fallback or "unknown"
    code = vss_id.lstrip(".")
    if not code:
        return fallback or "unknown"
    return code


# ---------------------------------------------------------------------------
# Internal helpers – format detection
# ---------------------------------------------------------------------------


def _detect_format(content: str, url: str) -> str:
    """Detect whether a subtitle payload is YouTube XML or json3 format.

    Detection order:
    1. Inspect the first non-whitespace character of *content*.
    2. Fall back to the URL extension.

    Args:
        content: Raw subtitle file content.
        url: Source URL (used for extension-based fallback).

    Returns:
        ``"xml"`` or ``"json3"``.
    """
    stripped = content.lstrip()
    if stripped.startswith("<?xml") or stripped.startswith("<"):
        return "xml"
    if stripped.startswith("{") or stripped.startswith("["):
        return "json3"
    parsed = urlparse(url)
    path_lower = parsed.path.lower()
    if path_lower.endswith(".xml") or "xml" in path_lower:
        return "xml"
    if path_lower.endswith(".json3") or "json3" in path_lower:
        return "json3"
    return "xml"


# ---------------------------------------------------------------------------
# Internal helpers – XML parsing
# ---------------------------------------------------------------------------


def _parse_xml_caption(xml_content: str) -> list[SubtitleCue]:
    """Extract subtitle cues from YouTube's timed-text XML format.

    YouTube's XML format wraps cues in ``<p>`` elements inside a root
    ``<transcript>`` element.  Each ``<p>`` element has ``t`` (start ms)
    and ``d`` (duration ms) attributes.  The cue text is a sequence of
    ``<s>`` (sub-word) elements concatenated together.

    Args:
        xml_content: Raw XML string from the YouTube subtitle endpoint.

    Returns:
        Ordered list of :class:`SubtitleCue` objects.
    """
    cues: list[SubtitleCue] = []

    try:
        root = ET.fromstring(xml_content)
    except ET.ParseError as exc:
        _logger.error("Failed to parse XML caption: %s", exc)
        return cues

    p_elements = root.findall(_XML_CUE_TAG)
    if not p_elements:
        p_elements = root.findall(".//" + _XML_CUE_TAG)

    for index, p_elem in enumerate(p_elements):
        try:
            cue = _xml_element_to_cue(p_elem, index)
            if cue is not None:
                cues.append(cue)
        except Exception as exc:
            _logger.warning(
                "Skipping XML cue at index %d: %s", index, exc
            )
            continue

    _logger.debug("Parsed %d XML cue(s).", len(cues))
    return cues


def _xml_element_to_cue(p_elem: ET.Element, index: int) -> Optional[SubtitleCue]:
    """Convert a single XML ``<p>`` element to a :class:`SubtitleCue`.

    Args:
        p_elem: The XML element representing one caption cue.
        index: Zero-based sequential index assigned to this cue.

    Returns:
        A :class:`SubtitleCue`, or ``None`` if the element is malformed.
    """
    start_str: str = p_elem.get("t", "")
    duration_str: str = p_elem.get("d", "")

    if not start_str:
        return None

    try:
        start_ms = int(start_str)
        duration_ms = int(duration_str) if duration_str else 0
    except ValueError:
        return None

    text_parts: list[str] = []
    for child in p_elem.iter():
        if child.tag == _XML_TEXT_TAG and child.text:
            text_parts.append(child.text or "")
        elif child.tag == _XML_CUE_TAG and child.text and child is p_elem:
            text_parts.append(child.text or "")
    raw_text = p_elem.text or ""
    for child in p_elem:
        if child.text:
            raw_text += child.text
        if child.tail:
            raw_text += child.tail

    text = raw_text.strip()
    text = _normalise_subtitle_text(text)

    end_ms = start_ms + max(duration_ms, _estimate_duration_ms(text))

    return SubtitleCue(index=index, start_ms=start_ms, end_ms=end_ms, text=text)


def _estimate_duration_ms(text: str) -> int:
    """Estimate a display duration for a text string in milliseconds.

    Uses a heuristic of 150 ms per character as a minimum, with a floor
    of 1 second and a ceiling of 5 seconds for short cues.

    Args:
        text: The subtitle text.

    Returns:
        Estimated display duration in milliseconds.
    """
    char_count = len(text)
    if char_count == 0:
        return 1000
    estimated = int(char_count * 150)
    return max(1000, min(estimated, 5000))


def _xml_cue_to_srt(cue: SubtitleCue, index: int) -> str:
    """Convert a single :class:`SubtitleCue` to an SRT entry string.

    Args:
        cue: The subtitle cue to convert.
        index: The 1-based SRT entry index.

    Returns:
        A string in SRT entry format::

            1
            00:00:01,000 --> 00:00:04,000
            Hello, world!

    """
    lines = _split_srt_text(cue.text)
    time_line = (
        f"{_format_srt_time(cue.start_ms)} --> "
        f"{_format_srt_time(cue.end_ms)}"
    )
    entry_lines = [str(index), time_line] + lines
    return "\n".join(entry_lines)


# ---------------------------------------------------------------------------
# Internal helpers – json3 parsing
# ---------------------------------------------------------------------------


def _parse_json3_caption(json3_content: str) -> list[SubtitleCue]:
    """Extract subtitle cues from YouTube's json3 caption format.

    The json3 format is a JSON object with an ``"events"`` array.  Each
    event has ``t`` (start offset in milliseconds), ``d`` (duration in
    milliseconds), and ``segs`` (an array of ``{"utf8": "..."}`` dicts).

    Args:
        json3_content: Raw json3 string from the YouTube subtitle endpoint.

    Returns:
        Ordered list of :class:`SubtitleCue` objects.
    """
    cues: list[SubtitleCue] = []

    try:
        data = _safe_json_loads(json3_content)
    except (ValueError, TypeError) as exc:
        _logger.error("Failed to parse json3 caption: %s", exc)
        return cues

    events: list[dict] = _get_nested(data, _JSON3_EVENTS_KEY, default=[])

    cue_index = 0
    for event in events:
        if not isinstance(event, dict):
            continue

        event_type = event.get("_gtsv", "") or event.get("type", "")
        if event_type and event_type not in ("", "text"):
            continue

        start_ms_raw = event.get("t", 0)
        duration_ms_raw = event.get("d", 0)
        segs: list[dict] = event.get("segs", [])

        if not segs:
            continue

        try:
            start_ms = int(start_ms_raw)
        except (TypeError, ValueError):
            start_ms = 0

        try:
            duration_ms = int(duration_ms_raw)
        except (TypeError, ValueError):
            duration_ms = 0

        text_parts: list[str] = []
        for seg in segs:
            if isinstance(seg, dict):
                utf8_chunk = seg.get(_JSON3_UTF8_KEY, "")
                if utf8_chunk:
                    text_parts.append(utf8_chunk)

        raw_text = "".join(text_parts)
        text = _normalise_subtitle_text(raw_text.strip())

        if not text:
            continue

        end_ms = start_ms + max(duration_ms, _estimate_duration_ms(text))

        cue = SubtitleCue(index=cue_index, start_ms=start_ms, end_ms=end_ms, text=text)
        cues.append(cue)
        cue_index += 1

    _logger.debug("Parsed %d json3 cue(s).", len(cues))
    return cues


def _json3_cue_to_srt(cue: SubtitleCue, index: int) -> str:
    """Convert a single json3-sourced :class:`SubtitleCue` to SRT entry.

    Identical to :func:`_xml_cue_to_srt` but separated for clarity and
    future format-specific customisation.

    Args:
        cue: The subtitle cue to convert.
        index: The 1-based SRT entry index.

    Returns:
        A string in SRT entry format.
    """
    return _xml_cue_to_srt(cue, index)


# ---------------------------------------------------------------------------
# Internal helpers – format converters
# ---------------------------------------------------------------------------


def _convert_xml_to_srt(xml_content: str) -> str:
    """Convert YouTube XML caption content to SRT format.

    Args:
        xml_content: Raw XML string from YouTube.

    Returns:
        SRT-formatted string.
    """
    cues = _parse_xml_caption(xml_content)
    return convert_to_srt(cues)


def _convert_json3_to_srt(json3_content: str) -> str:
    """Convert YouTube json3 caption content to SRT format.

    Args:
        json3_content: Raw json3 string from YouTube.

    Returns:
        SRT-formatted string.
    """
    cues = _parse_json3_caption(json3_content)
    return convert_to_srt(cues)


# ---------------------------------------------------------------------------
# Internal helpers – SRT formatting
# ---------------------------------------------------------------------------


def _format_srt_time(ms: int) -> str:
    """Format a millisecond timestamp as an SRT timecode ``HH:MM:SS,mmm``.

    Handles negative values by clamping to zero.  Values exceeding 24 hours
    are allowed (SRT spec permits it) but displayed without day rollover.

    Args:
        ms: Time offset in milliseconds.

    Returns:
        A string of the form ``"HH:MM:SS,mmm"``.
    """
    ms = max(ms, 0)
    hours, remainder = divmod(ms, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    seconds, milliseconds = divmod(remainder, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{milliseconds:03d}"


def _cue_to_srt_entry(cue: SubtitleCue) -> str:
    """Build a single SRT entry block from a :class:`SubtitleCue`.

    Args:
        cue: The subtitle cue.

    Returns:
        A multi-line SRT entry block string.
    """
    return _xml_cue_to_srt(cue, cue.index + 1)


def _split_srt_text(text: str, max_chars_per_line: int = 42) -> list[str]:
    """Split subtitle text into SRT-compatible lines.

    SRT convention limits each line to roughly 42 characters and at most
    two lines per cue.  Long words are kept intact where possible.

    Args:
        text: The raw subtitle text (may contain ``\\n`` for hard breaks).
        max_chars_per_line: Maximum characters per output line.

    Returns:
        A list of 1 or 2 strings.
    """
    hard_blocks = text.split("\\n")
    result: list[str] = []
    for block in hard_blocks:
        if len(block) <= max_chars_per_line:
            result.append(block)
        else:
            wrapped = _soft_wrap(block, max_chars_per_line)
            result.extend(wrapped[:2])
    return result[:2] if result else [""]


def _soft_wrap(text: str, max_chars: int) -> list[str]:
    """Wrap *text* into lines of at most *max_chars* characters.

    Breaks are inserted at whitespace boundaries.  Falls back to a hard
    split at *max_chars* when no whitespace is available.

    Args:
        text: Text to wrap.
        max_chars: Maximum line length.

    Returns:
        List of wrapped lines.
    """
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        if current and len(current) + 1 + len(word) > max_chars:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}" if current else word
    if current:
        lines.append(current)
    if not lines:
        lines = [text[:max_chars]]
    return lines


def _normalise_subtitle_text(text: str) -> str:
    """Clean up raw caption text into a display-ready string.

    - Strips XML/HTML-like tags that may appear in the text.
    - Decodes common HTML entities.
    - Collapses runs of whitespace.
    - Removes common non-speech filler tags used by YouTube ASR.

    Args:
        text: Raw caption text.

    Returns:
        Cleaned caption text.
    """
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"&amp;", "&", text)
    text = re.sub(r"&lt;", "<", text)
    text = re.sub(r"&gt;", ">", text)
    text = re.sub(r"&quot;", '"', text)
    text = re.sub(r"&#39;", "'", text)
    text = re.sub(r"&nbsp;", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# ---------------------------------------------------------------------------
# Internal helpers – general utilities
# ---------------------------------------------------------------------------


def _safe_json_loads(json_str: str) -> Any:
    """Parse a JSON string with lenient error handling.

    Args:
        json_str: JSON-encoded string.

    Returns:
        Parsed Python object.

    Raises:
        ValueError: If *json_str* is not valid JSON.
    """
    import json as _json

    try:
        return _json.loads(json_str)
    except _json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON: {exc}") from exc


def _get_nested(
    data: Any, key: str, default: Any = None
) -> Any:
    """Safely retrieve a top-level key from a dict.

    Args:
        data: The dict (or any object) to query.
        key: Key to look up.
        default: Value to return if *key* is absent.

    Returns:
        The value for *key*, or *default*.
    """
    if isinstance(data, dict):
        return data.get(key, default)
    return default


def _seconds_to_ms(seconds: float) -> int:
    """Convert floating-point seconds to integer milliseconds.

    Args:
        seconds: Time in seconds.

    Returns:
        Equivalent time in milliseconds (rounded to nearest integer).
    """
    return int(round(seconds * 1000))


# ---------------------------------------------------------------------------
# Internal helpers – URL utilities
# ---------------------------------------------------------------------------


def _clean_subtitle_url(url: str) -> str:
    """Remove unnecessary query parameters from a subtitle URL.

    Strips tracking parameters that may cause problems when downloading
    subtitle files, while preserving the essential ``baseUrl`` components.

    Args:
        url: Raw subtitle URL.

    Returns:
        Cleaned URL string.
    """
    parsed = urlparse(url)
    keep_params = {
        "baseurl",
        "expire",
        "signature",
        "sig",
        "n",
        "player",
        "title",
    }
    qp = parse_qs(parsed.query, keep_blank_values=True)
    filtered = {k: v for k, v in qp.items() if k.lower() in keep_params}
    new_query = urlencode(filtered, doseq=True)
    return urlunparse(parsed._replace(query=new_query))
